### ISSUE TITLE
cot->react & react->cot

### ISSUE THREAD

**Issue by huangjf11** [ysymyth/ReAct#8]
Hello, I would like to ask if there is a code implementation for cot ->react and react ->cot mentioned in the paper

你好，我想问一下论文里提到的cot->react 和 react->cot 有代码实现吗

**Comment by ysymyth** [comment]
Hi, I don't have the code at hand right now (it might be somewhere inside Google), but the implementation should be very simple:

- run both CoT (n samples) and ReAct (1 sample)
- CoT -> ReAct: use CoT majority vote if it is voted > n/2 times, otherwise use ReAct
- ReAct -> CoT: use ReAct if it doesn't time out, otherwise use CoT majority vote

let me know if you need more help!

**Comment by ysymyth** [comment]
I'll close it for now, but feel free to open new issues if needed.
